[build.environment]
  NODE_VERSION = "16"

[build]
  publish = ".vitepress/dist"
  command = "pnpm run build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "frame-ancestors '*';"
